@ReactApp.Server_HostAddress = http://localhost:5182

GET {{ReactApp.Server_HostAddress}}/weatherforecast/
Accept: application/json

###register api test
POST {{ReactApp.Server_HostAddress}}/account/register
Content-Type: application/json
Accept: application/json

{
    "UserName": "admin",
    "Email": "Admin@gmail.com",
    "Password": "Admin@123"
}

###


